import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Pill } from "../ui/Pill";
import { b64urlDecodeToString } from "../protocol/encode";
import type { PhiInvoiceV1, PhiSettlementV1 } from "../protocol/types";
import { decodePayloadFromFile } from "../transport/ingestTransport";
import { matchesInvoice } from "../protocol/settlement";
import { postToLocalChannel } from "../transport/broadcastChannelTransport";
import {
  deriveSettlementFromSendSigilFileForInvoice,
  markSendSigilUsedFromMeta,
} from "../transport/sigilSettlement";
import { PhiGlyph } from "../ui/PhiGlyph";
import { formatPhiDisplay } from "../pricing/amountModel";

type PayStatus = "WAITING" | "SETTLED" | "ERROR";

function parseInvoiceFromUrl(url: string): PhiInvoiceV1 | null {
  try {
    const parsed = new URL(url);
    const r = parsed.searchParams.get("r") ?? new URLSearchParams(parsed.hash.replace(/^#/, "")).get("r");
    if (!r) return null;
    const json = b64urlDecodeToString(r);
    const payload = JSON.parse(json) as { v?: string };
    if (payload && payload.v === "PHI-INVOICE-1") return payload as PhiInvoiceV1;
    return null;
  } catch {
    return null;
  }
}

function shortKey(key: string) {
  if (!key) return "";
  return `${key.slice(0, 6)}…${key.slice(-4)}`;
}

export function PayView() {
  const [invoice, setInvoice] = useState<PhiInvoiceV1 | null>(null);
  const [status, setStatus] = useState<PayStatus>("WAITING");
  const [msg, setMsg] = useState<string | null>(null);
  const [receivedSettlement, setReceivedSettlement] = useState<PhiSettlementV1 | null>(null);

  useEffect(() => {
    const inv = parseInvoiceFromUrl(window.location.href);
    if (!inv) {
      setStatus("ERROR");
      setMsg("Missing or invalid invoice link.");
      return;
    }
    setInvoice(inv);
  }, []);

  const amountDisplay = useMemo(() => {
    if (!invoice) return "—";
    return formatPhiDisplay(invoice.amount.phi);
  }, [invoice]);

  const handleReceiptFile = useCallback(async (file: File) => {
    if (!invoice) {
      setMsg("Invoice not loaded.");
      setStatus("ERROR");
      return;
    }
    const payload = await decodePayloadFromFile(file);
    if (payload && payload.v === "PHI-SETTLEMENT-1") {
      if (!matchesInvoice(payload, invoice)) {
        setMsg("Send sigil does not match this invoice.");
        setStatus("ERROR");
        return;
      }
      if (payload.toPhiKey !== invoice.merchantPhiKey) {
        setMsg("Send sigil is addressed to a different merchant.");
        setStatus("ERROR");
        return;
      }
      postToLocalChannel(payload);
      setReceivedSettlement(payload);
      setStatus("SETTLED");
      setMsg("Send sigil received. Payment closed and forwarded.");
      return;
    }

    const derived = await deriveSettlementFromSendSigilFileForInvoice(file, invoice);
    if (!derived) {
      setMsg("Could not parse the send sigil file.");
      setStatus("ERROR");
      return;
    }

    markSendSigilUsedFromMeta(derived.meta);
    postToLocalChannel(derived.settlement);
    setReceivedSettlement(derived.settlement);
    setStatus("SETTLED");
    setMsg("Send sigil received. Payment closed and forwarded.");
  }, [invoice]);

  const tone = status === "SETTLED" ? "ok" : status === "ERROR" ? "warn" : "neutral";

  return (
    <div className="pt-pay">
      <div className="pt-card pt-payCard">
        <div className="pt-cardInner">
          <div className="pt-payHeader">
            <div className="pt-h1">Pay Invoice</div>
            <Pill tone={tone as any} text={status} />
          </div>

          {invoice ? (
            <div className="pt-payInvoice">
              <div className="pt-payRow">
                <span className="pt-muted">Merchant</span>
                <span>{invoice.merchantLabel || shortKey(invoice.merchantPhiKey) || "Merchant"}</span>
              </div>
              <div className="pt-payRow">
                <span className="pt-muted">Amount</span>
                <span className="pt-inlineAmount">
                  <PhiGlyph className="pt-phiIcon pt-phiIcon--inline" />
                  {amountDisplay}
                </span>
              </div>
              {invoice.memo ? (
                <div className="pt-payRow">
                  <span className="pt-muted">Memo</span>
                  <span>{invoice.memo}</span>
                </div>
              ) : null}
              <div className="pt-payRow">
                <span className="pt-muted">Invoice</span>
                <span>{shortKey(invoice.invoiceId)}</span>
              </div>
            </div>
          ) : null}

          <div className="pt-divider" />

          <div className="pt-payActions">
            <div className="pt-payHint">
              Upload the send sigil generated by VerifierStamper to close this payment.
            </div>
            <label className="pt-btn primary" style={{ cursor: "pointer" }}>
              Upload Send Sigil
              <input
                type="file"
                accept=".svg,.json,.zip,application/json,application/zip,image/svg+xml"
                style={{ display: "none" }}
                onChange={(e) => {
                  const f = e.target.files?.[0] ?? null;
                  if (f) void handleReceiptFile(f);
                  e.currentTarget.value = "";
                }}
              />
            </label>
            {receivedSettlement ? (
              <div className="pt-payReceipt">
                <div className="pt-muted">Receipt</div>
                <div>{shortKey(receivedSettlement.settlementId)}</div>
              </div>
            ) : null}
          </div>

          {msg ? <div className="pt-statusMessage">{msg}</div> : null}
        </div>
      </div>
    </div>
  );
}
