export const S = {
  full: {
    width: "100vw",
    maxWidth: "100vw",
    height: "100dvh",
    maxHeight: "100dvh",
    margin: 0,
    padding: 0,
    overflow: "hidden",
  } as const,
  viewport: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: "100%",
    maxWidth: "100vw",
    overflow: "hidden",
  } as const,
  gridBar: { display: "grid", gridTemplateColumns: "1fr auto", alignItems: "center" } as const,
  stickyTabs: { position: "sticky", top: 48, zIndex: 2 } as const,
  mono: { overflowWrap: "anywhere" } as const,
  iconBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    padding: 0,
    flex: "0 0 auto",
  } as const,
  iconBtnSm: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    padding: 0,
    flex: "0 0 auto",
  } as const,
  modalBody: { flex: "1 1 auto", minHeight: 0, overflowY: "auto", overflowX: "hidden", paddingBottom: 80 } as const,
  headerImg: { maxWidth: "64px", height: "auto", flex: "0 0 auto" } as const,
  valueStrip: { overflowX: "auto", whiteSpace: "nowrap" } as const,

  /* Minimal inline popover safety (we’ll replace with CSS next) */
  popBg: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 9999,
    background: "rgba(0,0,0,.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
  },
  popCard: {
    width: "min(980px, 100%)",
    maxHeight: "min(680px, calc(100dvh - 28px))",
    borderRadius: 18,
    overflow: "hidden",
    background: "rgba(8,10,16,.92)",
    border: "1px solid rgba(255,255,255,.12)",
    boxShadow: "0 24px 70px rgba(0,0,0,.6)",
    display: "flex",
    flexDirection: "column" as const,
  },
  popHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "12px 12px 10px 14px",
    borderBottom: "1px solid rgba(255,255,255,.08)",
  },
  popBody: {
    flex: "1 1 auto",
    minHeight: 0,
    overflow: "auto",
    padding: 10,
  },
  popTitle: { fontSize: 12, color: "rgba(255,255,255,.82)", letterSpacing: ".02em" },
};
